export const LOAD_FROM_ITUNES = "LOAD_FROM_ITUNES";
export const LOAD_FROM_SPOTIFY = "LOAD_FROM_SPOTIFY";

export const LOAD_FROM_ITUNES_SUCCESS = "LOAD_FROM_ITUNES_SUCCESS";
export const LOAD_FROM_SPOTIFY_SUCCESS = "LOAD_FROM_SPOTIFY_SUCCESS";

export const LOAD_ERROR = "LOAD_ERROR";
export const LOAD_ERROR_RESET = "LOAD_ERROR_RESET";


export const SET_SEARCH_TERM = "SET_SEARCH_TERM";